// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs9QtuS6ejMqJACRDTpud8b9dfPKUPgXA',
    appId: '1:405044080767:web:f6368cdf8619a60f254f4a',
    messagingSenderId: '405044080767',
    projectId: 'mmm-flutter-project',
    authDomain: 'mmm-flutter-project.firebaseapp.com',
    storageBucket: 'mmm-flutter-project.appspot.com',
    measurementId: 'G-GD2VM22037',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1zBRBf2lytK_AJjVu_Pge2Ws_0MW1MVc',
    appId: '1:405044080767:android:64d9685b9cc90981254f4a',
    messagingSenderId: '405044080767',
    projectId: 'mmm-flutter-project',
    storageBucket: 'mmm-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4ROjNDBmuIwq6AZfx8Dcv0kO3DlUrLZw',
    appId: '1:405044080767:ios:1ec59ffc6d18feb1254f4a',
    messagingSenderId: '405044080767',
    projectId: 'mmm-flutter-project',
    storageBucket: 'mmm-flutter-project.appspot.com',
    iosBundleId: 'com.example.mmmProject',
  );
}
